### ISSUE TITLE
YoochooseBuy Preprocess

### ISSUE THREAD

**Issue by DiMarzioBian** [FDUDSDE/CoPE#2]
Hi,
Im currently writing a paper while using your model as a baseline.
However I cannot preprocess he YoochooseBuy dataset to your level.
Would you mind sharing your processed data or how you do the preprocess with me?

Thanks and best regards

**Comment by DiMarzioBian** [comment]
Hello,
Could you kindly also share your tuned hypermeters with us.
We are trying to report the variance of the result but we dont have much time for WWW'23.

Thank you very much

**Comment by yzhang1918** [comment]
Hi,
Please check this link for the processed YoochooseBuy dataset:
https://drive.google.com/file/d/1JO6wWEn9rhbJuvDm7qQ5Er4l41xZRmUa/view?usp=sharing

**Comment by DiMarzioBian** [comment]
Well received, thank you.

**Comment by yzhang1918** [comment]
> Hello, Could you kindly also share your tuned hypermeters with us. We are trying to report the variance of the result but we dont have much time for WWW'23.
> 
> Thank you very much

Sorry, I didn't find the intermediate log files but the aggregated results😅.
You could use the following results.
MRR   = 0.0113 std = 0.0009
R@10 = 0.0191 std = 0.0013

Or maybe you could try the default hyperparameters.
Though we used grid search, but the default hyperparameters work fine in most cases (if I remembered correctly).

**Comment by DiMarzioBian** [comment]
Alright, still appreciated for solving my question at weekends. Thanks for the help.
